# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-22 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('avatar', models.ImageField(upload_to='avatar/', verbose_name='头像')),
                ('signature', models.CharField(max_length=90, verbose_name='个性签名')),
                ('gender', models.CharField(max_length=1, verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
