# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-22 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30, verbose_name='来源')),
                ('title', models.CharField(max_length=300, verbose_name='新闻标题')),
                ('release_time', models.DateField(verbose_name='发布时间')),
                ('introduction', models.CharField(max_length=90, verbose_name='新闻简介')),
                ('content', models.TextField(verbose_name='新闻内容')),
                ('category', models.CharField(max_length=30, verbose_name='新闻类别')),
                ('click_number', models.IntegerField(default=0, verbose_name='点击量')),
                ('avatar', models.ImageField(upload_to='', verbose_name='来源头像')),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
