# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-23 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='news',
            name='click_number',
        ),
        migrations.RemoveField(
            model_name='news',
            name='introduction',
        ),
        migrations.AddField(
            model_name='news',
            name='comment_number',
            field=models.IntegerField(default=0, verbose_name='评论数量'),
        ),
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(default=11, upload_to='', verbose_name='新闻图片'),
            preserve_default=False,
        ),
    ]
