# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-23 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20191023_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='新闻图片'),
        ),
    ]
