# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-23 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20191023_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.CharField(max_length=200, null=True, verbose_name='新闻图片'),
        ),
    ]
